#! /bin/sh
# Author: Markus Stenberg <markus.stenberg@iki.fi>
# Copyright (C) 2012 cisco Systems, Inc.

# By default, hnet isn't started, even if part of image.
# The reason for this is mostly that (for example) random IPv4 address
# on a router after first boot is bloody pain to deal with. 

# Much better to run the /etc/init.d/hnet start (or enable) by hand,
# as needed.

/etc/init.d/hnet disable

exit 0
