#!/bin/sh 
#-*-sh-*-
#
# $Id: use-v4 $
#
# Author: Markus Stenberg <fingon@iki.fi>
#
#  Copyright (c) 2012 cisco Systems, Inc.
#
# Created:       Tue Oct 30 13:30:44 2012 mstenber
# Last modified: Tue Oct 30 15:28:54 2012 mstenber
# Edit time:     14 min
#

stop() {
    # XXX - how to get rid of only one v4 NAT rule? or does it matter?
    iptables -t nat -F POSTROUTING

    # Clear DNS parameters in SKV
    skvtool \
        "dhcp-dns.$interface=" \
        "dhcp-dns-search.$interface="
}

start() {
    # Run only if we actually got an address
    if [ "x$new_ip_address" = "x" ]
    then
        return
    fi

    # Set up the NAT
    # XXX - get the 10.0.0.0/8 from SKV 
    PREFIX=10.0.0.0/8
    #iptables -t nat -A POSTROUTING -o $interface -s $PREFIX -j MASQUERADE
    iptables -t nat -A POSTROUTING -o $interface -j MASQUERADE

    # Set up DNS parameters in SKV
    skvtool \
        "dhcp-dns.$interface=${new_domain_name_servers}" \
        "dhcp-dns-search.$interface=${new_domain_search}"
}


case $reason in
    BOUND)
        start
        ;;
    RENEW|REBIND)
        #stop
        #start
        ;;
    DEPREF|EXPIRE|RELEASE|STOP)
        stop
	;;
esac

