#!/bin/sh
#-*-sh-*-
#
# $Id: use-pd $
#
# Author: Markus Stenberg <fingon@iki.fi>
#
# Created:       Tue Jul 24 11:01:51 2012 mstenber
# Last modified: Fri Mar  8 11:37:59 2013 mstenber
# Edit time:     55 min
#

start() {
    if [ "x$new_ip6_prefix" = x ]
    then
        return
    fi

    life=""
    if [ ! "x$new_preferred_life" = x ]
    then
        value=`lua -e "print(os.time()+$new_preferred_life)"`
        life="$life\"pref\":$value,"
    fi
    if [ ! "x$new_max_life" = x ]
    then
        value=`lua -e "print(os.time()+$new_max_life)"`
        life="$life\"valid\":$value,"
    fi

    # Just manipulate BIRD state

    ARG="pd.$interface+={$life\"prefix\":\"${new_ip6_prefix}\",\"dns\":\"${new_dhcp6_name_servers}\",\"dns_search\":\"${new_dhcp6_domain_search}\",\"pclass\":\"${new_dhcp6_prefix_class}\"}"
    #echo "calling skvtool $ARG" >> /tmp/use-pd.log

    # Remove old + then add new, in one atomic-ish transaction (hooray)
    skvtool \
        "pd.$interface-={\"prefix\":\"${new_ip6_prefix}\"}" \
        "$ARG"
}

stop() {
    if [ "x$old_ip6_prefix" = x ]
    then
        return
    fi

    args="stop ${new_ip6_prefix} ${interface}"

    # Just manipulate BIRD state
    skvtool \
        "pd.$interface-={\"prefix\":\"${old_ip6_prefix}\"}" \
        "pd.$interface-={\"prefix\":\"${new_ip6_prefix}\"}"
}

echo `date` $reason $interface : ${old_ip6_prefix} / ${new_ip6_prefix} >> /tmp/use-pd.log

case $reason in
    BOUND6)
        start
        ;;
    RENEW6|REBIND6)
        stop
        start
        ;;
    DEPREF6|EXPIRE6|RELEASE6|STOP6)
        stop
	;;
esac
